[default]
ELASTICSEARCH_URL = "https://ait-es-data-02.us.archive.org:9200"
ELASTICSEARCH_INDEX = "gifcities"
ELASTICSEARCH_USER = "gifcities"
ELASTICSEARCH_PASSWORD = "lol"
ELASIICSEARCH_CERT = "~/es_http_ca.crt"
ELASTICSEARCH_TIMEOUT=30
DEBUG = false
BLOB_URL = "https://blob.gifcities.org/gifcities"

[test]

[development]
ELASTICSEARCH_URL = "http://localhost:9200"
DEBUG = true

[qa]

[prod]
