[default]
ELASTICSEARCH_URL = "https://ait-es-data-02.us.archive.org:9200"
ELASTICSEARCH_INDEX = "gifcities"
ELASTICSEARCH_USER = "gifcities"
ELASTICSEARCH_PASSWORD = "lol"
ELASTICSEARCH_CERT = "~/es_http_ca.crt"
ELASTICSEARCH_TIMEOUT=30
DEBUG = false
BLOB_URL = "https://blob.gifcities.org/gifcities"
EMBEDDING_MODEL = "ViT-L-14"
EMBEDDING_PRETRAIN = "laion2b_s32b_b82k"

[test]

[development]
ELASTICSEARCH_URL = "http://localhost:9200"
DEBUG = true

[qa]

[prod]
